name: all_for_moms_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_slider_drawer: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  build_runner:
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
